### ISSUE TITLE
我用flutter做了一个自动打包上传的

### ISSUE THREAD

**Issue by 18598925736** [LazyIonEs/AndroidToolsKit#1]

**Comment by LazyIonEs** [comment]
谢谢你在我们的开源项目上提出问题。然而，我们的开源项目并不是用于广告或推广个人或商业产品的平台。我们的目标是为开发者社区提供有价值的技术支持和解决方案，而非作为广告渠道。希望你能理解。

如果你对项目本身有任何建议或反馈，我们会很乐意听取。
